### ISSUE TITLE
Original results reproduction

### ISSUE THREAD

**Issue by AwesomeLemon** [attilanagy234/ENAS-pytorch#1]
Hi,

Could you tell me whether you've been able to reproduce the ENAS results for CNN training?

**Comment by attilanagy234** [comment]
Hey!

Sorry for the late reply! We produced this code for a research competiton. You can see the resulting work here: http://tdk.bme.hu/VIK/DownloadPaper/Neuralis-architektura-kereses-minta1

You will find our results in Chapter 3, that we could not reach the performance of the original paper. We did not have much time (and computational resources) to optimize parameters in the end as we were approaching the deadline. 

We are planning to keep experiementing and try to pump up performance.

**Comment by AwesomeLemon** [comment]
Thanks for your answer!
